# Generated by Django 4.0.3 on 2022-03-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='list_names',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='requests',
            field=models.JSONField(default=dict),
        ),
    ]
