# Generated by Django 4.0.3 on 2022-03-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_choices',
            field=models.CharField(choices=[('todo', 'todo'), ('doing', 'doing'), ('done', 'done')], default='todo', max_length=5),
        ),
    ]
