# Generated by Django 4.0.3 on 2022-03-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_todo_todo_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='list_name',
            field=models.TextField(default=''),
        ),
    ]
